version: '3'
services:
  app:
    image: nvpryan/talenta-bot
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/${DB_NAME}
    restart: always
    cap_add:
      - SYS_ADMIN

  db:
    image: mongo:jammy
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb_data_container: