version: '3'
services:
  app:
    image: nvpryan/talenta-bot
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/${DB_NAME}

  db:
    image: mongo:jammy
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

volumes:
  mongodb_data_container: