name: Talenta Bot
on:
  push:
    branches:
      - main
jobs:
  build_main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-20.04
    env:
      ENV: ${{ secrets.ENV }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.16"
      - name: Authenticate to Docker Hub
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Create .env file
        run: |
          echo '${{ env.ENV }}' > .env
      - name: Build Project
        run: |
          ./bin/build.sh
  deploy_main:
    needs: [build_main]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to Docker Hub
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: Set SSH Keys and known_hosts
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -t rsa ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          echo "${{ secrets.SERVER_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Deploy on production
        run: |
          SERVER_USERNAME=${{ secrets.SERVER_USERNAME }} \
          SERVER_IP=${{ secrets.SERVER_IP }} \
          ./bin/deploy.sh production
